version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-security-jwt
    ports:
      - "5436:5436"
    networks:
      - default
    command: -p 5436

networks:
  default:

volumes:
  postgres: